apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-app

resources:
  - ../../base
  - route.yaml
  - serviceaccount.yaml
  - postgres-pv.yaml
  - hpa.yaml

patches:
  - path: backend-serviceaccount-patch.yaml
  - path: frontend-serviceaccount-patch.yaml
  - path: postgres-okd-patch.yaml

  - target:
      kind: ConfigMap
      name: app-config
    patch: |-
      - op: replace
        path: /data/CORS_ORIGINS
        value: https://task-app.apps.okd.diploma.test

  - target:
      kind: Deployment
      name: backend
    patch: |-
      - op: replace
        path: /spec/template/spec/initContainers/0/imagePullPolicy
        value: Always
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always

  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always

images:
  - name: ghcr.io/owner/repository-backend
    newName: image-registry.openshift-image-registry.svc:5000/task-app/backend
    newTag: latest
  - name: ghcr.io/owner/repository-frontend
    newName: image-registry.openshift-image-registry.svc:5000/task-app/frontend
    newTag: latest
